[package]
# General-Purpose Node Document
name = "gpnd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2.31"
polonius-the-crab = "0.4.0"

[dev-dependencies]
once_cell = "1.18.0"
